import type { Metadata } from 'next';
import { Spline_Sans, Bebas_Neue } from 'next/font/google';
import './globals.css';
import { Layout } from '../components';
import { SanityLive } from '../sanity/lib/live';

const splineSans = Spline_Sans({
  variable: '--font-spline-sans',
  subsets: ['latin'],
});

const bebasNeue = Bebas_Neue({
  variable: '--font-bebas-neue',
  subsets: ['latin'],
  weight: '400',
});

export const metadata: Metadata = {
  title: 'My Portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${splineSans.variable} ${splineSans.className} ${bebasNeue.variable} text-white antialiased`}
      >
        <SanityLive />
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
